const PrepareEval = {
 Vulnerables : {
    "function" : true ,
    "Function" : true ,
    "Reflect" : true ,
    "Proxy" : true ,
    "Error" : true ,
    "Intl" : true , 
    "Promise"     : true , 
    "RegExp" : true,
    "Array"     : true , 
    "Object"     : true , 
    "Map"     : true , 
    "new"      : true , 
    "async"     : true ,
    "await"     : true , 
    "yield" : true,
    "setTimeout" : true,
    "remove" : true,
    "import" : true,
    "super" : true,
    "arguments" :true,
    "delete" :true,
    "instance of" : true,
    "start" : true,
    "end" : true,
    "getElement" : true,
    "eval"     : true , 
    "exec"     : true , 
    "for"     : true , 
    "while"     : true , 
    "this"     : true , 
    "of"     : true , 
    "in"     : true , 
    "map"     : true , 
    "reduce" : true,
    "every" : true ,
    "each"     : true , 
    "forEach"     : true , 
    "WebAssembly" : true,
    "Bluetooth" : true,
    "fetch" : true,
    "then" : true,
    "Reqest" : true,
    "Service" : true,
    "Storage" : true,
    "Stream" : true,
    "Geolocation" : true,
    "Web" : true,
    "Image" : true,
    "Aes" : true,
    "Crypt" : true,
    "Animation" : true,
    "Audio" : true,
    "Auth" : true,
    "origin":true,
    "Pay":true,
    "Performance":true,
    "console":true,
    "Permission":true,
    "Canvas":true,
    "Client":true,
    "Range":true,
    "RTC":true,
    "setTimeout":true,
    "Worker":true,
    "window":true,
    "global":true,
    "Shadow":true,
    "Dom":true,
    "Element":true,
    "Speach":true,
    "Event":true,
    "post":true,
    "get":true,
    "put":true,
    "SVG":true,
    "File":true,
    "Form":true,
    "from":true,
    "html":true,
    "Html":true,
    "Time":true,
    "USB":true,
    "Video":true,
    "video":true,
    "audio":true,
    "Magnetometer":true,
    "Media":true,
    "XR":true,
    "CPU":true,
    "MIDI":true,
    "minetype":true,
    "MineType":true,
    "ms":true,
    "MS":true,
    "input":true,
    "Input":true,
    "install":true,
    "Install":true,
    "VR":true,
    "DB":true,
    "IDB":true,
    "Factory":true,
    "extend":true,
    "class":true,
    "Sensor":true,
    "Accelerometer":true
 } ,
 Check : 
    function (jsString,enables=[],disables=[]) {
       let vWords = JSON.parse(JSON.stringify ( this.Vulnerables ));
       for( let i = 0; i < enables.length ;i++){ vWords [enables[i]] = true; }
       for( let i = 0; i < disables.length ; i++){ vWords [disables[i]] = false; }
       for (const [word, enable] of Object.entries(vWords)) {
          if( enable && -1 !== jsString.indexOf(word) ) throw  word+' is a vulnerable word . ';
       }
}
}

module.exports = PrepareEval;